import type { Metadata } from "next";
import "@/styles/globals.scss";
import Message from "@/components/shared/message/Message";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Message message="Ação realizada com sucesso" type="error" />
        {children}
      </body>
    </html>
  );
}
