import {
  IoMenu,
  IoMail,
  IoPerson,
  IoKey,
  IoClose,
  IoWarning,
  IoHome,
  IoCall,
  IoBook,
  IoAdd,
  IoSearch,
  IoArrowBack,
  IoNewspaper,
  IoLogoInstagram,
  IoLogoYoutube,
  IoLogIn,
  IoLogOut,
  IoImage,
  IoTrash,
  IoPencil,
  IoChevronDown,
  IoChevronUp,
} from "react-icons/io5";
import { FaFacebookF } from "react-icons/fa";

const I = {
  Menu: IoMenu,
  Mail: IoMail,
  Person: IoPerson,
  Key: IoKey,
  Close: IoClose,
  Warning: IoWarning,
  Home: IoHome,
  Phone: IoCall,
  Book: IoBook,
  Add: IoAdd,
  Search: IoSearch,
  ArrowBack: IoArrowBack,
  Paper: IoNewspaper,
  Facebook: FaFacebookF,
  Instagram: IoLogoInstagram,
  Youtube: IoLogoYoutube,
  Login: IoLogIn,
  Logout: IoLogOut,
  Image: IoImage,
  Trash: IoTrash,
  Pencil: IoPencil,
  ArrowUp: IoChevronUp,
  ArrowDown: IoChevronDown,
};

export default I;
